IBNet_Avazu_001_0b212519:
    batch_norm: false
    batch_size: 10000
    cl_temp: 0.5
    cl_weight: 0.01
    dataset_id: Avazu_x4_h5
    debug_mode: false
    dnn_activations: pbmish_avazu
    dnn_hidden_units: [512, 512, 512]
    early_stop_patience: 2
    embedding_dim: 20
    embedding_regularizer: 0
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    gate_temp: 0.05
    group_id: null
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: IBNet
    model_id: IBNet_Avazu
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_cross_layers: 3
    num_workers: 3
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2023
    shuffle: true
    ssl_mode: true
    task: binary_classification
    use_features: null
    verbose: 1
IBNet_Avazu_002_b332ed89:
    batch_norm: false
    batch_size: 10000
    cl_temp: 0.5
    cl_weight: 0.01
    dataset_id: Avazu_x4_h5
    debug_mode: false
    dnn_activations: pbmish_avazu
    dnn_hidden_units: [512, 512, 512]
    early_stop_patience: 2
    embedding_dim: 20
    embedding_regularizer: 0
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    gate_temp: 0.1
    group_id: null
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: IBNet
    model_id: IBNet_Avazu
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_cross_layers: 3
    num_workers: 3
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2023
    shuffle: true
    ssl_mode: true
    task: binary_classification
    use_features: null
    verbose: 1
IBNet_Avazu_003_9888541b:
    batch_norm: false
    batch_size: 10000
    cl_temp: 0.5
    cl_weight: 0.01
    dataset_id: Avazu_x4_h5
    debug_mode: false
    dnn_activations: pbmish_avazu
    dnn_hidden_units: [512, 512, 512]
    early_stop_patience: 2
    embedding_dim: 20
    embedding_regularizer: 0
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    gate_temp: 0.15
    group_id: null
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: IBNet
    model_id: IBNet_Avazu
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_cross_layers: 3
    num_workers: 3
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2023
    shuffle: true
    ssl_mode: true
    task: binary_classification
    use_features: null
    verbose: 1
IBNet_Avazu_004_05676e81:
    batch_norm: false
    batch_size: 10000
    cl_temp: 0.5
    cl_weight: 0.01
    dataset_id: Avazu_x4_h5
    debug_mode: false
    dnn_activations: pbmish_avazu
    dnn_hidden_units: [512, 512, 512]
    early_stop_patience: 2
    embedding_dim: 20
    embedding_regularizer: 0
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    gate_temp: 0.2
    group_id: null
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: IBNet
    model_id: IBNet_Avazu
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_cross_layers: 3
    num_workers: 3
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2023
    shuffle: true
    ssl_mode: true
    task: binary_classification
    use_features: null
    verbose: 1
IBNet_Avazu_005_3aee6499:
    batch_norm: false
    batch_size: 10000
    cl_temp: 0.5
    cl_weight: 0.01
    dataset_id: Avazu_x4_h5
    debug_mode: false
    dnn_activations: pbmish_avazu
    dnn_hidden_units: [512, 512, 512]
    early_stop_patience: 2
    embedding_dim: 20
    embedding_regularizer: 0
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    gate_temp: 0.25
    group_id: null
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: IBNet
    model_id: IBNet_Avazu
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_cross_layers: 3
    num_workers: 3
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2023
    shuffle: true
    ssl_mode: true
    task: binary_classification
    use_features: null
    verbose: 1
IBNet_Avazu_006_95f8314c:
    batch_norm: false
    batch_size: 10000
    cl_temp: 0.5
    cl_weight: 0.01
    dataset_id: Avazu_x4_h5
    debug_mode: false
    dnn_activations: pbmish_avazu
    dnn_hidden_units: [512, 512, 512]
    early_stop_patience: 2
    embedding_dim: 20
    embedding_regularizer: 0
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    gate_temp: 0.3
    group_id: null
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: IBNet
    model_id: IBNet_Avazu
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_cross_layers: 3
    num_workers: 3
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2023
    shuffle: true
    ssl_mode: true
    task: binary_classification
    use_features: null
    verbose: 1
