IBNet_Avazu:
    model: IBNet
    dataset_id: Avazu_x4_h5
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.0e-3
    ssl_mode: True
    cl_weight: 0.01 #best
    cl_temp: 0.5 #best
    gate_temp: 0.1 #best
    embedding_regularizer: 0
    net_regularizer: 0
    batch_size: 10000
    embedding_dim: 20
    dnn_hidden_units: [512, 512, 512]
    dnn_activations: pbmish_avazu
    num_cross_layers: 3 #best
    net_dropout: 0
    batch_norm: False
    epochs: 100
    shuffle: True
    seed: 2023
    monitor: {'AUC': 1, 'logloss': -1}
    monitor_mode: 'max'

IBNet_Criteo:
    model: IBNet
    dataset_id: Criteo_x4_h5
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 5.e-4
    ssl_mode: True
    cl_temp: 0.5 #best
    cl_weight: 0.01 #best
    gate_temp: 0.3 #best
    embedding_regularizer: 1.e-4
    net_regularizer: 0
    batch_size: 10000
    embedding_dim: 20
    dnn_hidden_units: [1024, 1024, 1024]
    dnn_activations: pbmish_criteo
    num_cross_layers: 3
    net_dropout: 0.2
    batch_norm: True
    epochs: 100
    shuffle: True
    seed: 2023
    monitor: {'AUC': 1, 'logloss': -1}
    monitor_mode: 'max'

IBNet_Movielens:
    model: IBNet
    dataset_id: Movielenslatest_x1_h5
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.0e-3
    ssl_mode: True
    cl_temp: 1.0  #best
    cl_weight: 0.01  #best
    gate_temp: 1.0  #best
    embedding_regularizer: 0.01
    net_regularizer: 0
    batch_size: 10000
    embedding_dim: 20
    dnn_hidden_units: [400, 400, 400]
    dnn_activations: pbmish_avazu
    num_cross_layers: 3
    net_dropout: 0.1  #best
    batch_norm: True
    epochs: 100
    shuffle: True
    seed: 2023
    monitor: {'AUC': 1, 'logloss': -1}
    monitor_mode: 'max'