base_config: ./config/
base_expid: IBDCN_mask_Avazu  # DCN_20_Avazu, DCN_20_Criteo, AC_DCN_20_Avazu, AC_DCN_20_Criteo, IBNet_Avazu, IBNet_Criteo
dataset_id: Avazu_x4_h5  # Movielenslatest_x1_h5, Avazu_x4_h5, Criteo_x4_h5

# IBDCN_drop in Avazu
tuner_space:
    model_root: './checkpoints/'
    ssl_mode: True # 不对比
    cl_temp: [0.1, 0.5]
    cl_weight: [0.001, 0.01, 0.1]
    gate_temp: [0.1, 0.5]
    dnn_activations: pbmish_avazu
    num_cross_layers: 3
    net_dropout: 0.2
    seed: [1024, 2048, 4048]

# IBDCN_drop in Criteo
#tuner_space:
#    model_root: './checkpoints/'
#    ssl_mode: False # 不对比
#    cl_temp: 0.5 #best
#    cl_weight: 0.01 #best
#    gate_temp: 0.3 #best
#    dnn_activations: pbmish_criteo
#    num_cross_layers: 3
#    random_dropout: [0.25, 0.5, 0.75]
#    net_dropout: 0.2
#    batch_norm: True
#    seed: 2023

# IBDCN_drop in Movielens
#tuner_space:
#    model_root: './checkpoints/'
#    ssl_mode: False # 不对比
#    cl_temp: 1.0 #best
#    cl_weight: 0.01 #best
#    gate_temp: 1.0 #best
#    dnn_activations: pbmish_avazu
#    num_cross_layers: 3
#    random_dropout: [0.25, 0.5, 0.75]
#    net_dropout: 0.1 #best
#    batch_norm: True
#    seed: 2023

# ablation of cl_temp: IBNet_Avazu
#tuner_space:
#    model_root: './checkpoints/'
#    ssl_mode: True
#    cl_temp: [0.1, 0.3, 0.5, 0.7, 0.9, 2]
#    cl_weight: 0.01 #best
#    gate_temp: 0.1 #best
#    dnn_activations: pbmish_avazu
#    num_cross_layers: 3
#    net_dropout: 0
#    batch_norm: False
#    seed: 2023

# ablation of cl_temp: IBNet_Criteo
#tuner_space:
#    model_root: './checkpoints/'
#    ssl_mode: True
#    cl_temp: [0.1, 0.3, 0.5, 0.7, 0.9, 2]
#    cl_weight: 0.01 #best
#    gate_temp: 0.3 #best
#    dnn_activations: pbmish_criteo
#    num_cross_layers: 3
#    net_dropout: 0.2
#    batch_norm: True
#    seed: 2023

# ablation of gate_temp: IBNet_Avazu
#tuner_space:
#    model_root: './checkpoints/'
#    ssl_mode: True
#    cl_temp: 0.5 #best
#    cl_weight: 0.01 #best
#    gate_temp: [0.05, 0.1, 0.15, 0.2, 0.25, 0.3]
#    dnn_activations: pbmish_avazu
#    num_cross_layers: 3
#    net_dropout: 0
#    batch_norm: False
#    seed: 2023

# ablation of gate_temp: IBNet_Criteo
#tuner_space:
#    model_root: './checkpoints/'
#    ssl_mode: True
#    cl_temp: 0.5 #best
#    cl_weight: 0.01 #best
#    gate_temp: [0.1, 0.2, 0.3, 0.4, 0.5, 0.6]
#    dnn_activations: pbmish_criteo
#    num_cross_layers: 3
#    net_dropout: 0.2
#    batch_norm: True
#    seed: 2023

# heatmap of cross layer and dnn layer: IBNet_Avazu
#tuner_space:
#    model_root: './checkpoints/'
#    dnn_activations: pbmish_avazu
#    num_cross_layers: [1,2,3,4,5,6]
#    dnn_hidden_units: [[512], [512, 512], [512, 512, 512], [512, 512, 512, 512], [512, 512, 512, 512, 512], [512, 512, 512, 512, 512, 512]]

# heatmap of cross layer and dnn layer: IBNet_Criteo
#tuner_space:
#    model_root: './checkpoints/'
#    dnn_activations: pbmish_criteo
#    num_cross_layers: [1,2,3,4,5,6]
#    dnn_hidden_units: [[1024], [1024, 1024], [1024, 1024, 1024], [1024, 1024, 1024, 1024], [1024, 1024, 1024, 1024, 1024], [1024, 1024, 1024, 1024, 1024, 1024]]

# ablation of cross layer: AIB_DCNv4h_20_Avazu
#tuner_space:
#    model_root: './checkpoints/'
#    embedding_dim: 20
#    hidden_activations_correct: pbmish_avazu
#    hidden_activations_stabilize: pbmish_avazu
#    hidden_activations_accelerate: pbmish_avazu
#    num_cross_layers: [1,2,3,4,5,6]
#    ssl_mode: True
#    cl_weight: [0.005, 0.01, 0.02]
#    cl_temp: 0.5
#    gate_temp: 0.1
#    batch_norm: False
#    seed: 2023

# DCN_contain 23 activation functions
#tuner_space:
#    model_root: './checkpoints/'
#    embedding_dim: 20
#    dnn_activations: [relu, mish, dice, sigmoid, logsigmoid, softsign, softplus, hardsigmoid, prelu, gelu, elu, selu, silu, leaky_relu, hardswish, lelelu, vodice, simlift, xtan, simxtan, pxtan, simpxtan, tanhs]
#    num_cross_layers: 3
#    batch_norm: [False, True]
#    seed: 2023

# AIB_DCNv4h_20_Avazu
#tuner_space:
#    model_root: './checkpoints/'
#    embedding_dim: 20
#    hidden_activations_correct: pbmish_avazu
#    hidden_activations_stabilize: pbmish_avazu
#    hidden_activations_accelerate: pbmish_avazu
#    num_cross_layers: 3
#    ssl_mode: True
#    cl_weight: [0.01, 0.02]
#    cl_temp: [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0]
#    gate_temp: [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0]
#    batch_norm: False
#    seed: 2023

# AIB_DCNv4h_20_Criteo
#tuner_space:
#    model_root: './checkpoints/'
#    embedding_dim: 20
#    hidden_activations_correct: pbmish_criteo
#    hidden_activations_stabilize: pbmish_criteo
#    hidden_activations_accelerate: pbmish_criteo
#    num_cross_layers: 3
#    ssl_mode: True
#    cl_weight: 0.01
#    cl_temp: [0.1, 0.2, 0.3, 0.4, 0.5, 0.6]
#    gate_temp: [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0]
#    batch_norm: True
#    seed: 2023

# AC_DCN_quick_relu_only
#tuner_space:
#    model_root: './checkpoints/'
#    embedding_dim: 20
#    hidden_activations_correct: [ dice, selu, leaky_relu, lelelu, gelu, mish, prelu ]  #[simlift, lift, sigmoid, logsigmoid, softsign]  #[simlift, lift]  #[dice, selu, leaky_relu, lelelu]
#    hidden_activations_stabilize: [ sigmoid, logsigmoid, softsign ]  #[dice, selu, leaky_relu, lelelu]  #[simlift, lift]  #[simlift, lift, sigmoid, logsigmoid, softsign]
#    hidden_activations_accelerate: [ relu, mish ]  #[relu, prelu, gelu, mish]  #[simlift, lift]  #[relu, prelu, gelu, mish]
#    num_cross_layers: 3
#    batch_norm: [False, True]
#    seed: 2023

#tuner_space:
#    model_root: './checkpoints/'
#    embedding_dim: 20
#    hidden_activations_correct: [ dice, selu, leaky_relu, lelelu, gelu, mish, prelu ]  #[simlift, lift, sigmoid, logsigmoid, softsign]  #[simlift, lift]  #[dice, selu, leaky_relu, lelelu]
#    hidden_activations_stabilize: [ vodice, simlift, xtan, xxtan, bxtan, bxxtan, simxtan, pxtan, tanhs ]  #[dice, selu, leaky_relu, lelelu]  #[simlift, lift]  #[simlift, lift, sigmoid, logsigmoid, softsign]
#    hidden_activations_accelerate: [ relu ]  #[relu, prelu, gelu, mish]  #[simlift, lift]  #[relu, prelu, gelu, mish]
#    num_cross_layers: 3
#    batch_norm: [False]
#    seed: 2023

# AC_DCN_refinement, modify num_cross_layers
#tuner_space:
#    model_root: './checkpoints/'
#    embedding_dim: 20
#    hidden_activations_correct: [ dice, selu, leaky_relu, lelelu, gelu, mish, prelu ]  #[simlift, lift, sigmoid, logsigmoid, softsign]  #[simlift, lift]  #[dice, selu, leaky_relu, lelelu]
#    hidden_activations_stabilize: [ sigmoid, logsigmoid, softsign ]  #[dice, selu, leaky_relu, lelelu]  #[simlift, lift]  #[simlift, lift, sigmoid, logsigmoid, softsign]
#    hidden_activations_accelerate: [ relu ]  #[relu, prelu, gelu, mish]  #[simlift, lift]  #[relu, prelu, gelu, mish]
#    num_cross_layers: 3
#    batch_norm: [False, True]
#    seed: 2023

# AC_DCN_quick_test
#tuner_space:
#    model_root: './checkpoints/'
#    embedding_dim: 20
#    hidden_activations_correct: [ dice, selu, leaky_relu, lelelu, gelu, mish, prelu ]  #[simlift, lift, sigmoid, logsigmoid, softsign]  #[simlift, lift]  #[dice, selu, leaky_relu, lelelu]
#    hidden_activations_stabilize: [ sigmoid, logsigmoid, softsign ]  #[dice, selu, leaky_relu, lelelu]  #[simlift, lift]  #[simlift, lift, sigmoid, logsigmoid, softsign]
#    hidden_activations_accelerate: [ relu, gelu, mish ]  #[relu, prelu, gelu, mish]  #[simlift, lift]  #[relu, prelu, gelu, mish]
#    batch_norm: [False, True]
#    seed: 2023

# AC_DCN_new_backup
#tuner_space:
#    model_root: './checkpoints/'
#    embedding_dim: 20
#    hidden_activations_correct: [ dice, selu, leaky_relu, lelelu, gelu, mish, prelu ]  #[simlift, lift, sigmoid, logsigmoid, softsign]  #[simlift, lift]  #[dice, selu, leaky_relu, lelelu]
#    hidden_activations_stabilize: [ sigmoid, logsigmoid, softsign, simlift, xtan, simxtan, pxtan, simpxtan, tanhs ]  #[dice, selu, leaky_relu, lelelu]  #[simlift, lift]  #[simlift, lift, sigmoid, logsigmoid, softsign]
#    hidden_activations_accelerate: [ relu ]  #[relu, prelu, gelu, mish]  #[simlift, lift]  #[relu, prelu, gelu, mish]
#    batch_norm: [False, True]
#    seed: 2023

# AC_DCN
#tuner_space:
#    model_root: './checkpoints/'
#    embedding_dim: 10
#    hidden_activations_correct: [ dice, selu, leaky_relu, lelelu, simlift, gelu, mish ]  #[simlift, lift, sigmoid, logsigmoid, softsign]  #[simlift, lift]  #[dice, selu, leaky_relu, lelelu]
#    hidden_activations_stabilize: [ sigmoid, logsigmoid, softsign, dice, selu, leaky_relu, lelelu, simlift, relu, prelu, gelu, mish ]  #[dice, selu, leaky_relu, lelelu]  #[simlift, lift]  #[simlift, lift, sigmoid, logsigmoid, softsign]
#    hidden_activations_accelerate: [ relu ]  #[relu, prelu, gelu, mish]  #[simlift, lift]  #[relu, prelu, gelu, mish]
#    batch_norm: [False, True]
#    seed: 2023
